baseurl = "https://c2c-ctf-2025.org"
enablerobotstxt = true
paginate = 50
timezone = "America/New_York"
titlecasestyle = "Go"
relativeURLs = false
canonifyURLs = true


[languages.en]
languagecode = "en-us"
languagedirection = "ltr"
languagename = "English"
weight = 10

[languages.en.params.paige]
# copyright = "© Will Faught"
description = "A CTF Organized by Northeastern University"
title = "C2C CTF 2025"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["html", "paige-search"]
section = ["html"]
taxonomy = ["html"]
term = ["html"]

[params.paige.list_page]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true

[params.paige.page]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true

[[params.paige.feed.atom.authors]]
email = "example@example.com"
name = "John Doe"
url = "https://example.com"

[params.paige.feed.rss]
managing_editor = "example@example.com (John Doe)"
web_master = "example@example.com (John Doe)"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[params.paige.theme]
primary_color = "#CC0000" # Red
secondary_color = "#000000" # Black
background_color = "#FFFFFF" # White
link_color = "#CC0000"
hover_color = "#990000" # Darker shade of Red for hover effects
text_color = "#000000"

[params]
custom_css = "/css/custom.css" 